trigger:
- main

pool: Selfhosted Azure Devops Agents

steps:
- checkout: self
  persistCredentials: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    appType: 'webAppLinux'
    appName: 'moss-jira-app'
    runtimeStack: 'PYTHON|3.11'
    package: '$(System.DefaultWorkingDirectory)'
    startUpCommand: 'streamlit run app/main.py'
