trigger:
  - main

pool: Selfhosted Azure Devops Agents

variables:
  azureSubscription: ARM-CCC-DPMS-ont-01
  appName: test-streamlit-app
  resourceGroup: rg-dpms-ont-weu-01
  region: westeurope
  sku: B1
  appServicePlan: moss-jira-app-plan
  runtime: PYTHON:3.11

steps:
  - checkout: self
    persistCredentials: true
    # clean: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(runtime)
      architecture: 'x64'
  
  - task: ArchiveFiles@2
    inputs:
      rootFolder: $(Build.SourcesDirectory)  # Where your project lives
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'deployment.zip'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp up \
          --name $(appName) \
          --resource-group $(resourceGroup) \
          --location $(region) \
          --sku $(sku) \
          --plan $(appServicePlan) \
          --runtime $(runtime) \
          --log-level verbose

          



# jobs:
#   - job: Deployment
#     displayName: 'Deploy Streamlit App'
#     steps:
#     - checkout: self
#       persistCredentials: true
#       clean: true

#     # Use Python version
#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '3.9'
#         addToPath: true

#     # Install dependencies from requirements.txt
#     - script: |
#         python3 -m venv .venv
#         source venv/bin/activate
#         python3 -m pip install --upgrade pip
#         pip3 install -r requirements.txt
#       displayName: 'Install Python dependencies'

#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: 'ARM-CCC-DPMS-ont-01'
#         scriptType: 'bash'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#             az webapp up --name test-streamlit-app --resource-group rg-dpms-ont-weu-01 --location europewest --src-path . --runtime "PYTHON|3.11"


    # # Add your deployment steps here
    # - task: AzureResourceGroupDeployment@2
    #   inputs:
    #     azureSubscription: 'ARM-CCC-DPMS-ont-01'
    #     action: 'Create Or Update Resource Group'
    #     resourceGroupName: 'rg-dpms-ont-weu-01'
    #     location: 'westeurope'
    #     templateLocation: 'Linked artifact'
    #     csmFile: 'azuredeploy.json'
    #     csmParametersFile: 'azuredeploy.parameters.json'
    #     deploymentMode: 'Incremental'
    #     # set working directory
    #     workingDirectory: $(System.DefaultWorkingDirectory)/streamlit-azure-deployment
