trigger:
  branches:
    include:
      - main
  
pool: Selfhosted Azure Devops Agents
  
variables:
  azureSubscription: ARM-CCC-DPMS-ont-01
  appName: moss-jira-app
  resourceGroup: rg-dpms-ont-weu-01

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp restart --name $(appName) --resource-group $(resourceGroup)
