trigger:
  - main
  
pool: Selfhosted Azure Devops Agents


jobs:
  - job: Deployment
    displayName: 'Deploy Streamlit App'
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
    
    # - task: AzureKeyVault@2
    #   displayName: 'Get Key Vault Secrets'
    #   inputs:
    #     azureSubscription: ${{ parameters.serviceConnection }}
    #     KeyVaultName: ${{ parameters.KeyVaultName }}
    #     SecretsFilter: '*'- task: UsePythonVersion@0
  

    # Azure Resource Deployment
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'ARM-CCC-DPMS-ont-01'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-dpms-ont-weu-01'
        location: 'westeurope'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        csmParametersFile: 'azuredeploy.parameters.json'
        deploymentMode: 'Incremental'

    # Deploying to Azure App Service
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ARM-CCC-DPMS-ont-01'
        appType: 'webAppLinux'
        appName: 'test-streamlit-app'
        runtimeStack: 'PYTHON|3.11'
        package: '$(System.DefaultWorkingDirectory)'
        # package: 'app/'
        startUpCommand: 'python -m streamlit hello --server.port 8000 --server.address localhost'
        