trigger:
- main

pool: Selfhosted Azure Devops Agents

steps:
- checkout: self
  persistCredentials: true

- script: |
    python -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive Artifacts'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
  displayName: 'Publish Artifacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    appType: 'webAppLinux'
    appName: 'moss-jira-app'
    runtimeStack: 'PYTHON|3.11'
    package: '$(Pipeline.Workspace)/drop/app.zip'  # Path to the artifact
    startUpCommand: 'streamlit run app/test.py'
    # enableCustomDeployment: true



# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'ARM-CCC-DPMS-ont-01'
#     appType: 'webAppLinux'
#     appName: 'moss-jira-app'
#     runtimeStack: 'PYTHON|3.11'
#     package: '$(System.DefaultWorkingDirectory)'
#     startUpCommand: 'streamlit run app/test.py'
