trigger:
  - main
  
pool: Selfhosted Azure Devops Agents

jobs:
  - job: Deployment
    displayName: 'Deploy Streamlit App'
    steps:
    - checkout: self
      persistCredentials: true
      # clean: true

    # # Use Python version
    # - task: UsePythonVersion@0
    #   inputs:
    #     versionSpec: '3.9'
    #     addToPath: true

    # # Install dependencies from requirements.txt
    # - script: |
    #     python3 -m venv .venv
    #     source venv/bin/activate
    #     python3 -m pip install --upgrade pip
    #     pip3 install -r requirements.txt
    #   displayName: 'Install Python dependencies'


    # Add your deployment steps here
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'ARM-CCC-DPMS-ont-01'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-dpms-ont-weu-01'
        location: 'westeurope'
        templateLocation: 'Linked artifact'
        csmFile: 'azuredeploy.json'
        csmParametersFile: 'azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
