variables:
  azureSubscription: 'ARM-CCC-DPMS-ont-01'
  appName: 'moss-jira-app'

trigger:
  - main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - task: ArchiveFiles@2
    displayName: 'Archive Artifacts'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/drop/app.zip' # Correct path to the artifact
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/drop
    artifact: drop
    displayName: 'Publish Artifacts'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      webAppName: '<YourAppName>' # Replace with your Azure App Service name
      package: '$(Pipeline.Workspace)/drop/app.zip'  # Correct path to the artifact
      enableCustomDeployment: true
