trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.6'
    addToPath: true

# Installing dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Azure Resource Deployment
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-dpms-ont-weu-01'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    # overrideParameters: '-parameter1 value1 -parameter2 value2'
    deploymentMode: 'Incremental'

# Deploying to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    appType: 'webAppLinux'
    appName: 'moss-jira-app'
    runtimeStack: 'PYTHON|3.11'
    package: '.'
    startUpCommand: 'streamlit run main.py'



