trigger:
- main

pool: Selfhosted Azure Devops Agents

steps:
- checkout: self

- script: docker build -t moss-jira-app:latest .
  displayName: 'Build image'

# - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD) your-container-registry.azurecr.io
#   displayName: 'Log in to container registry'

- script: docker push teammoss.azurecr.io/moss-jira-app:latest
  displayName: 'Push image to registry'

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.11'
#     addToPath: true

# # Installing dependencies
# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# # Azure Resource Deployment
# - task: AzureResourceGroupDeployment@2
#   inputs:
#     azureSubscription: 'ARM-CCC-DPMS-ont-01'
#     action: 'Create Or Update Resource Group'
#     resourceGroupName: 'rg-dpms-ont-weu-01'
#     location: 'westeurope'
#     templateLocation: 'Linked artifact'
#     csmFile: 'azuredeploy.json'
#     csmParametersFile: 'azuredeploy.parameters.json'
#     deploymentMode: 'Incremental'

# # Deploying to Azure App Service
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'ARM-CCC-DPMS-ont-01'
#     appType: 'webAppLinux'
#     appName: 'moss-jira-app'
#     runtimeStack: 'PYTHON|3.11'
#     package: '$(System.DefaultWorkingDirectory)'
#     # package: 'app/'
#     startUpCommand: 'streamlit run test.py'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ARM-CCC-DPMS-ont-01
    appType: 'webAppLinux'
    WebAppName: 'moss-jira-app'
    packageForLinux: 'teammoss.azurecr.io/moss-jira-app:latest'
