trigger:
- main

pool: Selfhosted Azure Devops Agents

steps:
- checkout: self
  persistCredentials: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ARM-CCC-DPMS-ont-01
    appType: 'webAppLinux'
    WebAppName: 'moss-jira-app'
    packageForLinux: 'teammoss.azurecr.io/moss-jira-app:latest'
