trigger:
  - main
  
pool:
  vmImage: ubuntu-latest
  
variables:
  azureSubscription: ARM-CCC-DPMS-ont-01
  appName: moss-jira-app
  resourceGroup: rg-dpms-ont-weu-01
  region: westeurope
  sku: B1
  appServicePlan: moss-jira-app-plan
  runtime: PYTHON:3.11

resources:
  repositories:
  - repository: myRepo
    type: git
    name: CloudCompetenceCenter/Datateam Moss/jira_process
    ref: main


steps:
- checkout: myRepo

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(System.DefaultWorkingDirectory)'
  