trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.6'
    addToPath: true

# Installing dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Azure Resource Deployment (checks if resources exist before deploying)
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'moss-rg'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '<Path_to_ARM_Template>'
    csmParametersFile: '<Path_to_ARM_Parameters>'
    overrideParameters: '-parameter1 value1 -parameter2 value2'
    deploymentMode: 'Incremental'

# Deploying to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ARM-CCC-DPMS-ont-01'
    appType: 'webAppLinux'
    appName: 'moss-jira-app'
    runtimeStack: 'PYTHON|3.11.6'
    package: '<Path_to_Your_App>'
    startUpCommand: 'streamlit run main.py'
