trigger:
  - main

pool: Selfhosted Azure Devops Agents

variables:
  azureSubscription: ARM-CCC-DPMS-ont-01
  appName: moss-jira-app
  resourceGroup: rg-dpms-ont-weu-01
  region: westeurope
  sku: B1
  appServicePlan: moss-jira-app-plan
  runtime: PYTHON:3.11

steps:
  - checkout: self
    persistCredentials: true
    # clean: true
    
  # - task: AzureWebApp@1
  #   inputs:
  #     azureSubscription: $(azureSubscription)
  #     appType: webAppLinux
  #     appName: $(appName)
  #     resourceGroupName: $(resourceGroup)
  #     package: '$(Pipeline.Workspace)/src'
  #     deploymentMethod: zipDeploy
  #     runtimeStack: 'PYTHON|3.11'
  #     appSettings: |
  #       - name: 'ENVIRONMENT_VAR_1' value: 'value1' 
  #       - name: 'ENVIRONMENT_VAR_2' value: 'value2'  

  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '3.11'
  #     architecture: 'x64'

  # - script: |
  #     set -x
  #     zip -rv deployment.zip * -x '*.git*'

  # - task: ArchiveFiles@2
  #   inputs:
  #     rootFolder: '$(Build.SourcesDirectory)'
  #     includeRootFolder: true
  #     archiveType: 'zip'
  #     archiveFile: 'deployment.zip'
  #     verbose: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp up \
          --name $(appName) \
          --resource-group $(resourceGroup) \
          --location $(region) \
          --sku $(sku) \
          --plan $(appServicePlan) \
          --runtime $(runtime)

          